### PR TITLE
file+https flake URI fails

### PR DESCRIPTION
**Pull request by goodlyrottenapple**
We are seeing the following error when trying to update to the latest version of this flake:

```
error: file:// URL 'file+https://github.com/ethereum/solc-bin/raw/f743ca7/macosx-amd64/list.json' has unexpected authority 'github.com'
```

Is there a reason to not use the original `https` only, without `file+`?

### CODE REVIEW

**Comment by hellwolf** [comment]
I am not sure tbh, I will look into it soon!

**Comment by hellwolf** [comment]
I took the documentation from:

```
file: Plain files or directory tarballs, either over http(s) or from the local disk.

In URL form, the schema must be file+http://, file+https:// or file+file://. If the extension doesn’t correspond to a known archive format (as defined by the tarball fetcher), then the file+ prefix can be dropped.
```

Which version of nix are you using?

**Comment by goodlyrottenapple** [comment]
I was seeing this on `nix (Nix) 2.13.3`

**Comment by hellwolf** [comment]
> I was seeing this on `nix (Nix) 2.13.3`

I am using 2.18, and the CI is using the latest.

Let me ask around if this was something new after 2.13.

**Comment by hellwolf** [comment]
Same in https://nix.dev/manual/nix/2.13/command-ref/new-cli/nix3-flake

**Comment by goodlyrottenapple** [comment]
I don't think this feature worked in 2.13.3. I tried a newer version of nix (2.18.2) which does indeed work correctly. Perhaps it's best to just update my version of nix.

**Comment by hellwolf** [comment]
> I don't think this feature worked in 2.13.3. I tried a newer version of nix (2.18.2) which does indeed work correctly. Perhaps it's best to just update my version of nix.

Okay, thanks for the confirmation. I should consider this closed then.

**Pull request closed without merging**
